# see https://github.com/opf/helm-charts/blob/main/charts/openproject/values.yaml

global:
  imagePullSecrets:
    - regcred-opicloud

dbInit:
  image:
    imagePullPolicy: "IfNotPresent"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  host: "openproject-poc.dev.opicloud.fr"
  tls:
    enabled: true
    secretName: "openproject-poc-dev-opicloud-fr-tls"

image:
  registry: "docker.io"
  repository: "openproject/openproject"
  imagePullPolicy: "IfNotPresent"
  tag: "17.7.2-slim"

hocuspocus:
  image:
    imagePullPolicy: "IfNotPresent"
 
openproject:
  https: true
  hsts: true

  admin_user:
    password: "admin"
    password_reset: "true"
    name: "OpenProject Admin"
    mail: "admin@example.net"

  useTmpVolumes: false

persistence:
  enabled: false

postgresql:
  bundled: true

s3:
  # S3 is required for attachment storage when storageClass does not
  # support ReadWriteMany
  enabled: true

  region: eu-west-par
  bucketName: openproject-poc

  endpoint: https://s3.eu-west-par.io.cloud.ovh.net/
  host: s3.eu-west-par.io.cloud.ovh.net
  port: 443
  pathStyle: true
  signatureVersion: 4
  enableSignatureV4Streaming: false

  directUploads: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

metrics:
  enabled: true

  ## Metrics endpoint path
  #
  path: "/metrics"

  ## Metrics port (added to service)
  #
  port: 9394

  ## ServiceMonitor configuration for Prometheus Operator
  #
  serviceMonitor:
    enabled: true

## Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if resources is set (resources is recommended for production).
## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
##
resourcesPreset: ~
## Configure resource requests and limits.
##
## http://kubernetes.io/docs/user-guide/compute-resources/
#
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
